apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-node-app
  template:
    metadata:
      labels:
        app: my-node-app
    spec:
      containers:
        - name: nginx
          image: bajajnodeappregistry.azurecr.io/nodejsapp
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-node-app-srvc
spec:
  selector:
    app: my-node-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer       
