apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: wpZiYWpham5vZGVhcHByZWdpc3RyeS5henVyZWNyLmlv
  password: c2xiYnc3UVdwaThjQ04wcWJ1ZEwrYldsa29rMFk2bUhXNXR5TmUzaWJoK0FDUkFaRXlWOQ==